sudo: required

language: generic

services:
  - docker

notifications:
  email:
    recipients:
      - spuetz@uos.de
    on_success: change
    on_failure: change

install:
  - docker build -t ros-lvr2 .

