lvr2_registration:
    icpIterations: 1
    icpMaxDistance: 9
    doGraphSLAM: true
    slamMaxDistance: 9
    loopSize: 10
    closeLoopDistance: 30
    verbose: true
    reduction: 0.4
lvr2_largescale_reconstruct:
    filePath: my_path/file.h5
    Ki: 20
    Kd: 20
    Kn: 20
    useGPU: false
    removeDanglingArtifacts: 10 
    fillHoles: 9
