name: noetic
on:
  push:
    branches:
      - 'develop'
      - 'noetic'
  pull_request:
    branches:
      - 'develop'
      - 'noetic'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_noetic:
    name: noetic
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout LVR2
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Compile LVR2 in ROS2 1 noetic WS
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: noetic
          ROS_REPO: main
          AFTER_SCRIPT: cd ~/target_ws && ./build/lvr2/bin/lvr2_reconstruct src/lvr2/dat/scan.pts